export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: false,
  lightTextDesc: true,
  topLine: "Charity never faileth",
  headline: "Make a world of difference by helping others",
  description: "Sign up and never miss a way to help out",
  buttonLabel: "Sing Up",
  imgStart: true,
  img: require("../../images/svg1.svg").default,
  alt: "Hearts",
  dark: true,
  primary: true,
  darkText: true,
};
export const homeObjTwo = {
  id: "about1",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Not sure where to start?",
  headline: "Browse through hundreds of different charitable causes",
  description:
    "We have you covered no matter where you are located. All you need is an internet connection and a phone or computer.",
  buttonLabel: " Look for a cause ",
  imgStart: false,
  img: require("../../images/svg2.svg").default,
  alt: "Piggybank",
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjThree = {
  id: "about2",
  lightBg: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "Did we miss something?",
  headline: "Please reach out and let us know!",
  description:
    "Help us grow of database of trustworthy organizations. All you need to do is send us a detail message and our team will reach out.",
  buttonLabel: "Start Now",
  imgStart: true,
  img: require("../../images/svg3.svg").default,
  alt: "Papers",
  dark: false,
  primary: false,
  darkText: true,
};
